### ISSUE TITLE
Error messages: batterycharge, carfinder, and statusreport not found

### ISSUE THREAD

**Issue by cbho** [arjenvrh/audi_connect_ha#5] opened 2019-06-20 18:19 UTC
Hi,
trying to get audi_connect to work - but get the error messages shown below.
My A3 is connected to "my audi" and I can track location data etc. using the audi app - so the connection is available.

My setup is 
hass.io: 0.94.3
audi_connect_ha:  all files updates as pr. today

configuration.yaml:
(have tried without "region", with EU, with DA, and DK - no difference - and yes, I checked my VIN number a zillion times).

Any suggestions what could be the problem?

Regards,
Chr.

```
audiconnect:
  username: '[not_published_here]'
  password: '[not_published_here]'
  region: EU
  scan_interval:
    minutes: 2
  name:
    [not_published_here]: 'Audi A3'
```

```
API error: {'errorCode': 'batterycharge.bs.entitynotfound', 'description': "entity '[not_published_here]' not found."}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
API error: {'errorCode': 'CF.security.9007', 'description': 'The service: carfinder_v1 for VIN: [not_published_here] could not be found.'}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
API error: {'errorCode': 'VSR.security.9007', 'description': 'The service: statusreport_v1 for VIN: [not_published_here] could not be found.'}
7:57 PM custom_components/audiconnect/audi_connect_account.py (ERROR) - message first occured at 7:55 PM and shows up 2 times
```

**Comment by arjenvrh** [comment] 2019-07-06 13:05
Certain API errors are normal if the corresponding service is not supported by the car or subscription. The message about the statusreport service however is not good, most of the sensors come from this service. Is the login itself successful? Did you enter the vin lower case?

**Comment by cbho** [comment] 2019-07-06 13:44
Hi,
Yes, the VIN-number is in lower case.
My own guess was, that the `batterycharge` could be a value related to hybrid vehicles and therefore not available on mine.
Not sure if the logon is successfull or not - I have not seen any error message about the logon not being successful - can I change the level of logging and find out?

Thanks for your help - would be really cool to get this working :-)

**Comment by arjenvrh** [comment] 2019-07-06 14:26
When upon HA start you're not getting any error like "Error logging into Audi API" the login should have been successful. So you are not seeing any sensors at all? Are you getting info such as range, tank level, oil level, etc in the myaudi app?

**Comment by cbho** [comment] 2019-07-06 15:17
When upon HA start you're not getting any error like "Error logging into Audi API" the login should have been successful.
_Then login seems to be succesful_
So you are not seeing any sensors at all? 
_Nope, none, what-so-ever_
Are you getting info such as range, tank level, oil level, etc in the myaudi app?
_Yes, works fine_

**Comment by arjenvrh** [comment] 2019-12-27 20:11
Unable to reproduce this error, closing this issue for now

**Closed by arjenvrh** 2019-12-27 20:11 UTC

**Comment by heumn** [comment] 2021-02-19 13:51
@cbho would you be able to share your account details with me in private over email (nikolai @ enode io ) and I would love to take a look at the endpoints your app is using. I will of course report back the findings here so that the bug can be fixed :)
