### ISSUE TITLE
Getting information from Audi fails, just 2 entities created

### ISSUE THREAD

**Issue by mbuzina** [arjenvrh/audi_connect_ha#50] opened 2020-10-27 19:43 UTC
I connected to myAudi account, but it only generated 2 entities (Car model and lock). Locking/unlocking fails, refreshing the data fails as well. Log entries:

    2020-10-27 09:15:43 ERROR (MainThread) [custom_components.audiconnect.util] Unable to refresh vehicle data of <vinsnipped>: 403, message='Forbidden', url=URL('https://msg.volkswagen.de/fs-car/bs/vsr/v1/Audi/DE/vehicles/<vinsnipped>/requests')
    2020-10-27 09:15:43 ERROR (MainThread) [custom_components.audiconnect.audi_account] Error refreshing vehicle data <vinsnipped> NoneType: None

**Comment by pergolafabio** [comment] 2020-10-29 15:33
i see the same behavour since the update this week with new auth token
in my case also 2 entities created
i tried adding intergration with/without region code 'DE' , no difference

additionally, when i do a resfresh service, i see this error below, not sure if its related

```
2020-10-27 18:48:26 ERROR (MainThread) [custom_components.audiconnect.util] Unable to refresh vehicle data of wauxxxx: 403, message='Forbidden', url=URL('https://msg.volkswagen.de/fs-car/bs/vsr/v1/Audi/DE/vehicles/WAUxxxx/requests')
2020-10-27 18:48:26 ERROR (MainThread) [custom_components.audiconnect.audi_account] Error refreshing vehicle data wauxxx
NoneType: None
```

**Comment by atozfugh** [comment] 2020-11-11 20:06
I have exactly the same issues. 
Is there already a fix for this?
Would be awesome if i could track my vehicle

**Comment by pergolafabio** [comment] 2020-11-11 20:07
No, not yet :-(

**Comment by dmelliott20** [comment] 2020-12-05 09:59
same issue here.....

**Comment by Je-sse** [comment] 2020-12-10 21:55
Same here

**Comment by wictorwilen** [comment] 2020-12-11 14:02
Yup, only two entities here as well :-(

**Comment by pergolafabio** [comment] 2020-12-16 12:40
i confirm, i bought a subscrition for 1 month , the audi remote and connect for 4,99
now, i have indeed more entities; so its a license issue that only 2 entitys were created

**Comment by Je-sse** [comment] 2020-12-16 13:16
I think its called "Audi Connect" in my country. But if I look at the functionalities it looks like it is already activated for my account? Were you able to check the information (like location of your car, fuel, door locks) in the myAudi app before?

**Comment by dmelliott20** [comment] 2020-12-16 13:18
its all activated on my account too.
________________________________

**Comment by atozfugh** [comment] 2020-12-16 13:21
Same for me.
In the application i can see my fuel level, door lock, location etc. So basically everything.

**Comment by pergolafabio** [comment] 2020-12-16 13:21
yes, i have my audi for 4 years now, i was able to use it for 3 years, now the license was expired
allthough it was a free service at first, i think somekind of package of my warranty
the warranty expired, so did my audi connect

i didnt see any fuel , and vehicle status anymore in app, so now i just did a test and renewed for 1 month, the basic edition, for 5€ / month
and now everything is back, and also on the android app too

**Comment by Je-sse** [comment] 2020-12-16 13:25
Ok, you didn't had to change anything in HA? It just showed up?

**Comment by pergolafabio** [comment] 2020-12-16 13:26
indeed, just showed up on a restart

**Comment by dmelliott20** [comment] 2020-12-16 13:30
I can see everything in the Audi app but just the two enties in HA. ive rebooted too.

the car is only 2 months old
________________________________

**Comment by pergolafabio** [comment] 2020-12-16 13:31
strange, maybe you have put the wrong country ? mine worked before, but stopped working

**Comment by dmelliott20** [comment] 2020-12-16 13:41
Ive tried leaving the country blank and DE. it was working before on a previous audi. but no luck with this one.

**Comment by Je-sse** [comment] 2020-12-16 13:48
Same here. Just deleted and added again with "DE" but nothing changed. Just "model" and "door lock"...

**Comment by dmelliott20** [comment] 2020-12-16 13:49
@Je-sse out of interest, what car have you got?

**Comment by Je-sse** [comment] 2020-12-16 13:50
A3 Sportback (just couple of weeks old)

**Comment by dmelliott20** [comment] 2020-12-16 13:52
ah! ive have an etron sportback - three weeks old. could be a theme

my previous etron worked flawlessly.
________________________________

**Comment by atozfugh** [comment] 2020-12-16 13:56
I got an A4 Avant. The 2021 Model - Maybe these cars are "to new" to work with this plugin.
If it helps someone i can share my audi login for troubleshooting :)

**Comment by pergolafabio** [comment] 2020-12-16 14:01
Don't think it's car dependent, cause it used the android app api info... For me it was just a license issue

**Comment by pergolafabio** [comment] 2020-12-16 14:02
I can test with your account if you want

**Comment by pergolafabio** [comment] 2020-12-16 14:02
Drop me a private on HA community forul

**Comment by dmelliott20** [comment] 2020-12-16 14:05
> Don't think it's car dependent, cause it used the android app api info... For me it was just a license issue

I can access the app fine though, its just HA that fails

**Comment by atozfugh** [comment] 2020-12-16 15:22
I will try it again today on another hass.io installation if it works. If not i'll contact you in the HA forum

**Comment by Risfinne** [comment] 2020-12-17 13:54
I experienced the same behavior with only 2 entities being created (Car model and Lock) until I changed the Region setting from "Sweden" to "SE". After that it started working like a charm.

**Comment by Je-sse** [comment] 2020-12-17 17:04
That also doesn't work for me. The documentation shows:
Set to 'DE' for Europe (or leave unset), to 'US' for North America, or to 'CN' for China.

Bought my car in the Netherlands, so it should be empty or DE. Both not working (NL also not)

**Comment by rklueber** [comment] 2021-01-19 18:42
Only two sensor (lock and type). Tried with “DE” and empty. Same issue.

**Comment by rholroyd** [comment] 2021-01-27 20:54
Also have the same problem with my Q5 in UK

**Comment by pergolafabio** [comment] 2021-01-27 21:05
In my case it was just a license issue, for test i extended my connect services for a month and all entities we're back... The month is passed , now back with 2 entities

**Comment by atozfugh** [comment] 2021-01-27 21:26
Well thats nice to know. How much did you pay for the expansion?
Still this doesn't make sense to me, because the App is showing every detail about my car. Maybe there is some API included in the subscription...

**Comment by pergolafabio** [comment] 2021-01-27 21:36
O believe it was 5€ a month,

**Comment by arandax** [comment] 2021-01-28 07:26
> In my case it was just a license issue, for test i extended my connect services for a month and all entities we're back... The month is passed , now back with 2 entities

How is your configuration set? I have a valid license, but I can't get this working.

**Comment by pergolafabio** [comment] 2021-01-28 07:31
Just email/password... Didn't fill in a region

**Comment by Risfinne** [comment] 2021-02-07 13:31
Now I am back to the same issue with my new Audi A6 that I bought a week ago.

My A4 Allroad is working fine, but my new A6 2021 only shows two entities even though everything works fine in the Audi app.

**Comment by dmelliott20** [comment] 2021-02-07 14:47
Same - the integration doesn’t appear to work with some new cars

Sent from my iPhone

On 7 Feb 2021, at 13:31, Risfinne <notifications@github.com> wrote:

﻿

Now I am back to the same issue with my new Audi A6 that I bought a week ago.

My A4 Allroad is working fine, but my new A6 2021 only shows two entities even though everything works fine in the Audi app.

**Comment by mmarcm** [comment] 2021-04-06 19:41
Hey @arjenvrh 
it seems that some interfaces for newer cars changed to something like this: prd.ece.vwg-connect.com.
The guys at ioBroker seems to use a home region (msg.volkswagen.de for older car models, and ...prd.ece.vwg-connect.com for newer cars) as homeregion setting.
See this: https://github.com/TA2k/ioBroker.vw-connect/blob/master/main.js
I think we need to differentiate between those interfaces. What do you think about it?

**Comment by arjenvrh** [comment] 2021-04-07 08:38
@mmarcm Thanks for the info, I added support for the different URLs. 
Could you please test and report back, my cars seem to be using the old APIs?

**Comment by mbuzina** [comment] 2021-04-07 08:56
> Could you please test and report back, my cars seem to be using the old APIs?

Yes, I have all the sensors now and I can access the functions! Great stuff @arjenvrh, thanks!

**Comment by dmelliott20** [comment] 2021-04-07 09:08
Thanks @arjenvrh mines all working too!!

**Comment by atozfugh** [comment] 2021-04-07 09:12
I can also confirm it! 👍  Mine is working like a charme now, thank you!!

**Comment by Risfinne** [comment] 2021-04-07 09:44
Confirmed working now with both my A4 2018 and A6 2021. 👍

**Comment by arandax** [comment] 2021-04-07 10:32
Awesome!
Now even my car shows up, thank you all!

**Comment by mbuzina** [comment] 2021-04-07 10:59
On last (minor) nitpick: the switch for the preheater does not notice that it has been turned off by the timer. I turned it on using hte switch and after 10 minutes it is turned off by the car, but ha does not notice the change. Do you poll the status regularly or can I add a trigger to poll if the preheater timer runs out?

**Comment by mmarcm** [comment] 2021-04-07 11:59
@arjenvrh looks very good! Thank you for the quick update! All entities are now created again and have the right information.

**Comment by devganny** [comment] 2021-04-07 12:26
Works like a charm now! Thanks a lot!

**Comment by rklueber** [comment] 2021-04-07 20:40
Woooohoooo. Works like a charm. 31 entities now. You are heros! Thank you.

**Closed** 2021-04-08 05:29 UTC

**Comment by JamieP83** [comment] 2021-04-08 14:47
Thanks for the help!

got a 2018 SQ5
I only had 2 entities as well, but then deleted it and added again with region as "DE" (caps) and i now have all 19 :)

**Comment by flaskett** [comment] 2021-04-08 20:35
I have been reading so many blogs to try and sort this problem of only 2 entities.
Deleted the integration, added the integration, tried the URLs above in the region field and no luck.
Deleted the integration, added the integration, tried DE in the region then restart the host and bingo, 29 entities!

**Comment by Rustymage** [comment] 2022-08-08 06:50
My car is outside the free connect trial and I only have 2 entities. Pretty annoying but I don't believe it's the apps fault.
