### ISSUE TITLE
Login to Audi service failed: 503, message='Service Unavailable', url=URL('https://app-api.live-my.audi.com/azs/v1/token'

### ISSUE THREAD

**Issue by titiviking** [arjenvrh/audi_connect_ha#94] opened 2021-11-26 14:18 UTC
`2021-11-26 10:50:56 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds 2021-11-26 10:51:16 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds 2021-11-26 10:51:28 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 503, message='Service Unavailable', url=URL('https://app-api.live-my.audi.com/azs/v1/token') 2021-11-26 11:00:02 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds 2021-11-26 11:00:13 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds 2021-11-26 11:00:25 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 503, message='Service Unavailable', url=URL('https://app-api.live-my.audi.com/azs/v1/token')`

Debug of custom component does not provide more details... HTTP component neither.

providing URL directly in browser does render some error response:
`no healthy upstream`

I have no clue though if it can be fixed through code by providing a new/correct endpoint, or if the problem is at audi side...

**Comment by derhappy** [comment] 2021-11-26 14:20
Same here, just as I restarted HA after an update.
Login with the credentials in browser and app is working fine

**Comment by derhappy** [comment] 2021-11-26 14:29
BTW, the official way to connect to audi is described here (but very useless, just one update per week is allowed). However, I can't figure out if the document contains some useful information for our use case:
https://www.audi.de/dam/nemo/extended-vehicle/ExVe_Technical_Integration_Guide.pdf

**Comment by JimRnewell** [comment] 2021-11-27 09:18
same here after a restart today, was fine before

**Comment by user45876** [comment] 2021-11-27 22:32
Unfortunately i have to confirm the issue.

**Comment by moorboss** [comment] 2021-11-29 09:56
Same here

**Comment by tornenen** [comment] 2021-11-29 11:17
same here

**Comment by mdshw5** [comment] 2021-11-29 14:15
Same. It would be wonderful (and too much to ask) for VW/Audi to give developers API access to their telematics services.

**Comment by Segran** [comment] 2021-11-29 14:42
It has been like that for a few days now, since I upgraded to HA 2021.5.

**Comment by Puppetmaster91** [comment] 2021-11-29 16:07
Same error as well, just watching this for a fix

**Comment by pilot1981** [comment] 2021-11-30 09:11
Audi developer changed again API services without any type of communication!

**Comment by derhappy** [comment] 2021-11-30 09:43
Well, of course they do. What we use here is not exactly approved by Audi to phrase it carefully ;-)
I guess they sell this data instead.

**Comment by unexxx** [comment] 2021-11-30 15:53
Same.

**Comment by PuckeyP** [comment] 2021-12-01 19:31
Same here. Watching this for a work around...

**Comment by t0bias-r** [comment] 2021-12-02 15:09
see #95

**Comment by user45876** [comment] 2021-12-02 16:59
Thank you so much!

However, I copied the four changed files into the appropriate folder in HA (twice) and restarted (twice) - for me, it is still giving an error when adding the integration:

On the first try:
Ungültige Anmeldeinformationen

Second try:
User input malformed

In HA, this is logged:
Logger: homeassistant.util.async_
Source: util/async_.py:132
First occurred: 17:37:47 (3 occurrences)
Last logged: 17:54:58

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for audiconnect doing I/O at custom_components/audiconnect/audi_services.py, line 612: markets_rsp = idkproxy_session.get(

Sorry, if I am holding it wrong.

**Comment by derhappy** [comment] 2021-12-02 19:46
Thanks for your investigation and quite extensive rewrite @t0bias-r !
Unfortunately I also get the authentication error, both with a limited and the main user. Both are working on the website.
It does not make any difference if I provide a region or not (I guess because DE is default in coding). 
I don't get anything in the logs, but this might be due to the log level I set.

**Comment by t0bias-r** [comment] 2021-12-02 20:13
What happens if you run the `test.py` instead?

**Comment by derhappy** [comment] 2021-12-02 20:28
xxx@i3serv:/usr/share/hassio/homeassistant/custom_components$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from audiconnect.audi_connect_account import AudiConnectAccount
  File "/usr/share/hassio/homeassistant/custom_components/audiconnect/__init__.py", line 3, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

**Comment by t0bias-r** [comment] 2021-12-03 05:51
hm...🤔
it seems that there is an issue in `test.py`.
pls change from
`task = main(main(sys.argv[1:]))`
to
`task = main(sys.argv[1:])`
and try again

**Comment by t0bias-r** [comment] 2021-12-03 07:13
I personally don't use home assistant. I just use the code as a systemd service that forwards the received values using Telnet/SSH to a different home automation system.
That means testing on my side is limited. But what I got from the error message is, that `Requests` class seems to be not usable in that way.
So I changed the code to use aiohttp requests provided by `AudiAPI` class instead of `Requests` class.

**Comment by user45876** [comment] 2021-12-03 07:39
Thanks again, @t0bias-r . I can confirm that the Login is now working again with the HA integration.
There is one small issue, though, that the name and model used to be the same as in the myAudi app - this is now empty.

So now the entities in HA are called 'none'. Does this make sense? I know you do not use HA, but the model / name parameter, which was filled before, seems to be empty now. Does that make any sense? ;)

**Comment by t0bias-r** [comment] 2021-12-03 08:30
That made sense, yes.
I changed the graphql query to retrieve more information --> see new commit.

Beside renderings and technical specs, the following items can be queried:
```
  "data": {
    "userVehicles": [
      {
        "vin": "WAUZxxxxxxxx",
        "mappingVin": "WAUZxxxxxxxx",
        "csid": "%csid%",
        "commissionNumber": null,
        "devicePlatform": "MBB",
        "mbbConnect": true,
        "userRole": {
          "role": "PRIMARY_USER"
        },
        "vehicle": {
          "classification": {
            "driveTrain": "PHEV"
          }
          "core": {
            "modelYear": 2020,
            "modelCoding": "4KA0WY"
          },
          "hifa": {
            "factoryPickupDateFrom": "2020-xx-yyT06:00:00.000+00:00",
            "factoryPickupDateTill": "2020-xx-yyT08:00:00.000+00:00",
            "fbDestination": "DEU760   B"
          },
          "media": {
            "shortName": "Audi A7 Sportback TFSI e",
            "longName": "Audi A7 Sportback TFSI e 50 TFSI e quattro S tronic"
          },
          "pdw": {
            "pdwVehicle": false
          },
        },
        "nickname": null
      }
    ]
  }
```

**Comment by Gunth** [comment] 2021-12-03 09:00
It is working back also for me in HA, just have somme errors in my logs about support_preheater, support_charger and support_climater. Don't have those options in my car that's maybe the reason ...
![image](https://user-images.githubusercontent.com/1955976/144574485-b7066dd5-cb47-437b-96c9-dd6d1a0bcafa.png)

**Comment by pilot1981** [comment] 2021-12-03 09:21
I don't find any test.py in this repository...

**Comment by user45876** [comment] 2021-12-03 09:25
I have to say that I am struggling - I can not add it anymore, no device and entities get made in HA. This is the error that is logged. I double checked and replaced the new files (2):

---
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_models.py:133
Integration: Audi Connect
First occurred: 10:21:24 (1 occurrences)
Last logged: 10:21:24

Error setting up entry spam1@meins.net for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 260, in get_vehicle_information
    response.parse(vins["data"])
  File "/config/custom_components/audiconnect/audi_models.py", line 149, in parse
    vehicle.parse(item)
  File "/config/custom_components/audiconnect/audi_models.py", line 133, in parse
    self.title = nickname
NameError: name 'nickname' is not defined
---

**Comment by derhappy** [comment] 2021-12-03 09:26
It's in the parent folder. You have to manually download it if you want to use it.
If you're running supervised (in Docker), you'll have to resolve some dependencies before you can use it (pip install xxx).

Danke @t0bias-r, for me it's working fine again with those changes done by you!
![grafik](https://user-images.githubusercontent.com/61394775/144578594-e5762118-6e24-4a2b-b2dc-147d9f0f19b1.png)

**Comment by derhappy** [comment] 2021-12-03 09:28
> I have to say that I am struggling - I can not add it anymore, no device and entities get made in HA. This is the error that is logged. I double checked and replaced the new files (2):
> 
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: homeassistant.config_entries Source: custom_components/audiconnect/audi_models.py:133 Integration: Audi Connect First occurred: 10:21:24 (1 occurrences) Last logged: 10:21:24
> ## Error setting up entry for audiconnect
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
> result = await component.async_setup_entry(hass, self) # type: ignore
> File "/config/custom_components/audiconnect/**init**.py", line 106, in async_setup_entry
> return await data.update(utcnow())
> File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
> if not await self.connection.update(None):
> File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
> vehicles_response = await self._audi_service.get_vehicle_information()
> File "/config/custom_components/audiconnect/audi_services.py", line 260, in get_vehicle_information
> response.parse(vins["data"])
> File "/config/custom_components/audiconnect/audi_models.py", line 149, in parse
> vehicle.parse(item)
> File "/config/custom_components/audiconnect/audi_models.py", line 133, in parse
> self.title = nickname
> NameError: name 'nickname' is not defined
> 
> sorry for the big font :-/

You'll have to manually change / copy all 4 files from the commit (ignore test.py). Or wait until @arjenvrh merged it and there's an update in HACS. Then restart HA and it should work.

**Comment by user45876** [comment] 2021-12-03 09:30
@derhappy I replaced all 4 files before, sure. Then i replaced the 2 newly changed. I even replaced all 4 again to double check ;) Which dependencies are you referring to?

**Comment by t0bias-r** [comment] 2021-12-03 09:31
I fixed the nickname issue. sorry for that.

**Comment by derhappy** [comment] 2021-12-03 09:32
The dependencies only come up when you try to execute test.py "outside" of your HA environment.

**Comment by user45876** [comment] 2021-12-03 09:37
@t0bias-r should there be a new commit?

**Comment by t0bias-r** [comment] 2021-12-03 10:09
> @t0bias-r should there be a new commit?

This commit https://github.com/arjenvrh/audi_connect_ha/pull/95/commits/ef91bf081d75e39dbc865227b50f0f5199ae86ef fixes this error:
>```
>File "/config/custom_components/audiconnect/audi_models.py", line 133, in parse
>self.title = nickname
>NameError: name 'nickname' is not defined
>```

**Comment by user45876** [comment] 2021-12-03 10:37
Yes, with this, for me everything is working again, thank you very much again, @t0bias-r . Your efforts are very much appreciated :)
(For the life of me I could not see the commit in the history - maybe it only took some more time.)

**Comment by JimRnewell** [comment] 2021-12-03 11:57
thank you, everything is back working again

**Comment by t0bias-r** [comment] 2021-12-03 15:09
> > > @t0bias-r should there be a new commit?
> > 
> > 
> > This commit [ef91bf0](https://github.com/arjenvrh/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) / [t0bias-r@ef91bf0](https://github.com/t0bias-r/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) fixes this error:
> > > ```
> > > File "/config/custom_components/audiconnect/audi_models.py", line 133, in parse
> > > self.title = nickname
> > > NameError: name 'nickname' is not defined
> > > ```
> 
> I don't have any "nickname" in audi_models.py

Look at this commit [ef91bf0](https://github.com/arjenvrh/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) / [t0bias-r@ef91bf0](https://github.com/t0bias-r/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) and ensure that your `audi_models.py` is up-to-date
![grafik](https://user-images.githubusercontent.com/95424140/144625224-5fe30806-4ffc-43cb-89c6-6bf898acc118.png)

**Comment by Segran** [comment] 2021-12-03 16:54
OK,  MOSTLY working after the changes from today, but: 
2021-12-03 17:43:11 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to update the vehicle position of WAUZZZF40JAxxxxxx: 204, message='No Content', url=URL('https://msg.volkswagen.de/fs-car/bs/cf/v1/Audi/DE/vehicles/WAUZZZF40JA0xxxxxxposition')

**Comment by SchwarzAxel** [comment] 2021-12-03 19:45
> The dependencies only come up when you try to execute test.py "outside" of your HA environment.
> 
> PS: Now i've got this error message too: support_preheater set to False: 502 Logger: custom_components.audiconnect.audi_connect_account Source: custom_components/audiconnect/audi_connect_account.py:557 Integration: Audi Connect

same here

**Comment by pilot1981** [comment] 2021-12-03 21:08
How I can force to update it on HA?

**Comment by adam760222** [comment] 2021-12-03 23:07
> Thanks again, @t0bias-r . I can confirm that the Login is now working again with the HA integration. There is one small issue, though, that the name and model used to be the same as in the myAudi app - this is now empty.
> 
> So now the entities in HA are called 'none'. Does this make sense? I know you do not use HA, but the model / name parameter, which was filled before, seems to be empty now. Does that make any sense? ;)

Can you please explain how you did it, as I still have Invalid credentials info when try to add integration...

**Comment by user45876** [comment] 2021-12-03 23:14
I replaced the 4 recently changed files from t0bias latest commit in the audiconnect folder on ha. You can also wait, until @arjenvrh merges the pull request and then update via hacs, restart ha and be done.

**Comment by vj80** [comment] 2021-12-03 23:28
Has anyone gotten this to work in the US?

**Comment by t0bias-r** [comment] 2021-12-04 08:42
> > Thanks again, @t0bias-r . I can confirm that the Login is now working again with the HA integration. There is one small issue, though, that the name and model used to be the same as in the myAudi app - this is now empty.
> > So now the entities in HA are called 'none'. Does this make sense? I know you do not use HA, but the model / name parameter, which was filled before, seems to be empty now. Does that make any sense? ;)
> 
> Can you please explain how you did it, as I still have Invalid credentials info when try to add integration...

I captured the network traffic of the latest Android myAudi app. Then I did some crypto analysis to understand which headers and requests are required

To me it looks like that Audi has changed all APIs not only the login. E.g. the API to enable/disable the climater is completely different to the current implemenation. I suspect that sooner or later these APIs will be disabled, too and have to be re-programmed.

**Comment by thorsten** [comment] 2021-12-04 08:43
The location doesn't return anything with the patch from @t0bias-r, everything else is currently working.

**Comment by adam760222** [comment] 2021-12-04 08:43
> I replaced the 4 recently changed files from t0bias latest [commit](https://github.com/arjenvrh/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) in the audiconnect folder on ha. You can also wait, until @arjenvrh merges the pull request and then update via hacs, restart ha and be done.

ok, so:
1. Replace 4 files in audiconnect folder
2. Add integration into Configuration -> Integration
3. insert Audi login data

For me I got invalid credential info.

**Comment by t0bias-r** [comment] 2021-12-04 08:44
> > The dependencies only come up when you try to execute test.py "outside" of your HA environment.
> > PS: Now i've got this error message too: support_preheater set to False: 502 Logger: custom_components.audiconnect.audi_connect_account Source: custom_components/audiconnect/audi_connect_account.py:557 Integration: Audi Connect
> 
> same here
> 
> 2021-12-03 20:59:53 ERROR (MainThread) [custom_components.audiconnect.util] Unable to start pre-heater of vehicle wauzzzf22mn075394: 502, message='Bad Gateway', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rs/v1/Audi/DE/vehicles/WAUZZZXXXXXXXXX/action')

To me it looks like that Audi has changed all APIs not only the login. E.g. the API to enable/disable the climater is completely different to the current implemenation. I suspect that sooner or later these APIs will be disabled, too and have to be re-programmed.
Currently, enabling the climater does not work on my Audi, too. I just can stop it.

**Comment by t0bias-r** [comment] 2021-12-04 09:10
> Has anyone gotten this to work in the US?

I've added a piece of code for US support.
Please try after applying these changes: https://github.com/t0bias-r/audi_connect_ha/commit/2ade26f26972139e7b3f34d7ab2c6570616588b2

**Comment by user45876** [comment] 2021-12-04 09:20
> > I replaced the 4 recently changed files from t0bias latest [commit](https://github.com/arjenvrh/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) in the audiconnect folder on ha. You can also wait, until @arjenvrh merges the pull request and then update via hacs, restart ha and be done.
> 
> ok, so:
> 
> 1. Replace 4 files in audiconnect folder
> 2. Add integration into Configuration -> Integration
> 3. insert Audi login data
> 
> For me I got invalid credential info.

Have you restarted HA? I also deleted the pycache files for good measure but I think that does absolutely nothing 😉

**Comment by adam760222** [comment] 2021-12-04 09:28
> > > I replaced the 4 recently changed files from t0bias latest [commit](https://github.com/arjenvrh/audi_connect_ha/commit/ef91bf081d75e39dbc865227b50f0f5199ae86ef) in the audiconnect folder on ha. You can also wait, until @arjenvrh merges the pull request and then update via hacs, restart ha and be done.
> > 
> > 
> > ok, so:
> > 
> > 1. Replace 4 files in audiconnect folder
> > 2. Add integration into Configuration -> Integration
> > 3. insert Audi login data
> > 
> > For me I got invalid credential info.
> 
> Have you restarted HA? I also deleted the pycache files for good measure but I think that does absolutely nothing 😉

Thanks! After restart works fine. Just I have missed oil level entitie, do you have the same?

**Comment by Segran** [comment] 2021-12-04 09:45
Thanks for the "fix", it looks like a total re-write.

I still get these 2 errors:
2021-12-04 10:35:46 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] support_climater set to False: 403
2021-12-04 10:35:46 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] support_charger set to False: 403

Why?

**Comment by titiviking** [comment] 2021-12-04 09:49
I got those too. My guess is that the API attempt to discover all functionalities, and that those are unavailable for your car.

I'm ignoring those as I don't have preheat or charger anyway, so even on error I don't care about it.

**Comment by Segran** [comment] 2021-12-04 11:47
I don't have a support_charger, so that may be a correct error, but I do have a heater - or is it a heater that exists only in e-cars?

**Comment by vj80** [comment] 2021-12-04 18:34
> > Has anyone gotten this to work in the US?
> 
> I've added a piece of code for US support. Please try after applying these changes: [t0bias-r@2ade26f](https://github.com/t0bias-r/audi_connect_ha/commit/2ade26f26972139e7b3f34d7ab2c6570616588b2)

Thank you! That worked!

**Comment by synack666** [comment] 2021-12-05 12:22
A big thanks for fixing, i love this tool.

**Closed** 2021-12-29 13:08 UTC
